name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simulate Deployment
        run: echo "Simulando deploy para ambiente de produção!"
